# Generated by Django 4.0.4 on 2022-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='place',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место проживания'),
        ),
    ]
