# Generated by Django 4.0.4 on 2022-06-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_note_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Записка', 'verbose_name_plural': 'Записки'},
        ),
    ]
